### ISSUE TITLE
Scroll snap stop: always

### ISSUE THREAD

**Issue by vasilich6107** [argyleink/gui-challenges#203] opened 2023-05-13 10:49 UTC
Hi. Im passing your challenges. When I try the demo "1 at a time" I can still scroll through the middle item without stopping. This reproducible on all browsers - Chrome/FF/Safari. I have a trackpad and swipe from left to right side allows me to do this trick.

Any ideas why it's happening?

https://github.com/argyleink/gui-challenges/assets/6721286/96d5c11f-1420-4c5a-8aa0-78a0adb46da6

**Comment by argyleink** [comment] 2023-05-15 17:23
yep! the user isnt forced to stop during a gesture, it's not going to steal it from you. but if you fling, it will rest at the "always" stops.

so this is by design, to let users have fluid gestures while their pointer is down. scroll-snap-stop always is more like a strong suggestion OR will only always if the user has flung. from my testing, trackpad users are the ones with the most control in this scenario, where like they have the most surface area to scroll past stops marked as always stop.

**Closed by argyleink** 2023-05-15 17:23 UTC
